# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='id',
        ),
        migrations.AlterField(
            model_name='classe',
            name='professor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Professor'),
        ),
    ]
