# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='igreja',
            name='plano',
            field=models.CharField(default='GRATUITO', max_length=100),
        ),
    ]
