# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-29 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_igreja_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igreja',
            name='nome_responsavel',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
