# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-29 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160629_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igreja',
            name='nome_igreja',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='igreja',
            name='nome_responsavel',
            field=models.CharField(max_length=100),
        ),
    ]
